import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {BridgeError} from './herdr.js';

const WINDOW = 2 * 1024 * 1024;
const PAGE_BYTES = 64 * 1024;
const uuid = /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
const digest = value => createHash('sha256').update(value).digest('hex');
const clip = value => typeof value === 'string' ? value.replace(/\x1b\[[0-?]*[ -/]*[@-~]/g, '').slice(0, 8000) : '';
const date = value => value && Number.isFinite(new Date(value).getTime()) ? new Date(value).toISOString() : null;
const unavailable = reason => ({available:false, source:'terminal', messages:[], hasMore:false, reason});
const encode = value => Buffer.from(JSON.stringify(value)).toString('base64url');
function cursorValue(value, identity) {
  if (!value) return null;
  try {
    if (typeof value !== 'string' || value.length > 512 || !/^[\w-]+$/.test(value)) throw Error();
    const parsed = JSON.parse(Buffer.from(value, 'base64url').toString());
    if (parsed.identity !== identity || !Number.isSafeInteger(parsed.before) || parsed.before < 0) throw Error();
    if (parsed.within !== undefined && (!Number.isSafeInteger(parsed.within) || parsed.within < 1 ||
        !Number.isSafeInteger(parsed.recordStart) || parsed.recordStart < 0 || parsed.recordStart >= parsed.before)) throw Error();
    return parsed;
  } catch { throw new BridgeError('history_changed', 'The conversation changed. Refresh history.', 409); }
}
function textBlocks(content) {
  if (typeof content === 'string') return clip(content);
  if (!Array.isArray(content)) return '';
  return clip(content.map(block => {
    if (['text','input_text','output_text'].includes(block?.type)) return block.text || '';
    if (block?.type === 'tool_result') return textBlocks(block.content);
    return ''; // Images, hidden reasoning, tool calls and provider metadata are not conversation text.
  }).filter(Boolean).join('\n\n'));
}
// Tool steps are context, not conversation: keep one short line, never a whole file or JSON payload.
const TOOL_TEXT = 600;
const toolText = value => { const text = clip(value).trim(); return text.length > TOOL_TEXT ? text.slice(0, TOOL_TEXT) + '…' : text; };
function toolSummary(input) {
  let value = input;
  if (typeof value === 'string') { try { value = JSON.parse(value); } catch { return toolText(value); } }
  if (!value || typeof value !== 'object') return toolText(String(value ?? ''));
  for (const key of ['command','cmd','file_path','path','pattern','query','url','description','prompt']) {
    const field = value[key];
    if (typeof field === 'string' && field.trim()) return toolText(field);
    if (Array.isArray(field) && field.every(part => typeof part === 'string')) return toolText(field.join(' '));
  }
  return toolText(JSON.stringify(value));
}
// Text the agent or terminal injects as a "user" turn. It is not something the person typed.
const injectedPrefixes = ['<system-reminder>','<local-command-','<command-name>','<command-message>','<command-args>','<bash-input>','<bash-stdout>','<bash-stderr>','<user-prompt-submit-hook>','<environment_context>','<user_instructions>','<permissions instructions>','<external_codex_apps_open_page>','<turn_aborted>','<collaboration_mode>','<skill>','# AGENTS.md instructions','Caveat: The messages below were generated by the user while running local commands'];
function userText(raw) {
  const text = raw.replace(/<system-reminder>[\s\S]*?<\/system-reminder>/g, '').trim();
  if (!text) return '';
  if (injectedPrefixes.some(prefix => text.startsWith(prefix))) return '';
  const reply = text.match(/^<send_user_message_question_reply>\s*([\s\S]*?)\s*<\/send_user_message_question_reply>$/);
  if (reply) {
    try {
      const answers = JSON.parse(reply[1]);
      const lines = (Array.isArray(answers) ? answers : [answers]).map(item => typeof item?.answer === 'string' ? item.answer : '').filter(Boolean);
      if (lines.length) return lines.join('\n');
    } catch { /* Fall through and show the reply as written. */ }
  }
  return text;
}
/** Parse documented transcript records into zero or more display messages. */
export function parseHistoryRecords(record, source, id) {
  const out = [];
  const add = (role, text, extra = {}) => { if (text) out.push({id:out.length ? `${id}.${out.length}` : id, role, text, timestamp:date(record.timestamp), ...extra}); };
  if (source === 'claude') {
    if (!['user','assistant'].includes(record.type) || record.isSidechain || record.isMeta) return out;
    const role = record.message?.role || record.type, content = record.message?.content;
    if (record.isCompactSummary) { add('system', 'Earlier conversation was compacted.'); return out; }
    if (role === 'user') {
      if (Array.isArray(content) && content.length && content.every(b => b.type === 'tool_result')) { add('tool', toolText(textBlocks(content))); return out; }
      const text = userText(textBlocks(content));
      if (text.startsWith('[Request interrupted')) add('system', 'Interrupted.');
      else add('user', text);
      return out;
    }
    if (typeof content === 'string') { add('assistant', clip(content)); return out; }
    if (!Array.isArray(content)) return out;
    add('assistant', textBlocks(content.filter(b => b?.type !== 'tool_result')));
    for (const block of content) if (block?.type === 'tool_use') add('tool', toolSummary(block.input), {toolName:clip(block.name) || 'Tool'});
  } else if (source === 'codex') {
    if (record.type !== 'response_item') return out;
    const item = record.payload;
    if (item?.type === 'message' && item.role === 'user') add('user', userText(textBlocks(item.content)));
    else if (item?.type === 'message' && item.role === 'assistant') add('assistant', textBlocks(item.content));
    else if (['function_call','custom_tool_call'].includes(item?.type)) add('tool', toolSummary(item.arguments ?? item.input), {toolName:clip(item.name) || 'Tool'});
    else if (['function_call_output','custom_tool_call_output'].includes(item?.type)) {
      let output = item.output;
      if (typeof output === 'string') {
        try { const parsed = JSON.parse(output); if (typeof parsed?.output === 'string') output = parsed.output; else if (Array.isArray(parsed)) output = parsed; } catch { /* Plain text output. */ }
      }
      if (Array.isArray(output)) output = output.map(part => typeof part?.text === 'string' ? part.text : '').filter(Boolean).join('\n');
      add('tool', toolText(typeof output === 'string' ? output : JSON.stringify(output)));
    }
  }
  return out;
}
function safeOpen(file, root) {
  const canonicalRoot = fs.realpathSync(root), canonical = fs.realpathSync(file);
  if (!canonical.startsWith(canonicalRoot + path.sep) || path.resolve(file) !== canonical) throw Error('outside_root');
  const fd = fs.openSync(file, fs.constants.O_RDONLY | fs.constants.O_NOFOLLOW | fs.constants.O_NONBLOCK);
  try {
    const stat = fs.fstatSync(fd);
    if (!stat.isFile() || stat.nlink !== 1 || fs.realpathSync(`/proc/self/fd/${fd}`) !== canonical) throw Error('changed');
    return {fd, stat};
  } catch (error) { fs.closeSync(fd); throw error; }
}
function locate(root, session, source) {
  if (session.kind === 'path') return typeof session.value === 'string' && session.value.endsWith('.jsonl') ? path.resolve(session.value) : null;
  if (!uuid.test(session.value)) return null;
  const suffix = `${session.value}.jsonl`;
  let inspected = 0;
  function walk(folder, depth) {
    if (depth > 4 || inspected > 10000) return null;
    let entries; try { entries = fs.readdirSync(folder, {withFileTypes:true}); } catch { return null; }
    for (const entry of entries) {
      if (++inspected > 10000) break;
      if (entry.isSymbolicLink()) continue;
      const file = path.join(folder, entry.name);
      if (entry.isFile() && (source === 'claude' ? entry.name === suffix : entry.name.startsWith('rollout-') && entry.name.endsWith('-' + suffix))) return file;
      if (entry.isDirectory()) { const found = walk(file, depth + 1); if (found) return found; }
    }
    return null;
  }
  return walk(root, 0);
}
export function createHistory(config) {
  const roots = {
    claude:config.historyRoots?.claude || path.join(config.homeDirectory, '.claude/projects'),
    codex:config.historyRoots?.codex || path.join(config.homeDirectory, '.codex/sessions'),
    opencode:config.historyRoots?.opencode || path.join(config.homeDirectory, '.local/share/opencode'),
  };
  return {async read(pane, cursor, known) {
    if (config.structuredHistory === false) return unavailable('History is disabled on this laptop.');
    const source = pane.agent, session = pane.agent_session;
    if (!Object.hasOwn(roots, source)) return unavailable('This agent does not provide supported structured history.');
    if (!session || !['id','path'].includes(session.kind) || typeof session.value !== 'string' || (session.agent && session.agent !== source)) return unavailable('Herdr has not reported a conversation identity yet. Live terminal output remains available.');
    if (source === 'opencode') return openCode(roots.opencode, session, cursor);
    let opened;
    try {
      const file = locate(roots[source], session, source);
      if (!file) return unavailable('The conversation file is not available yet.');
      opened = safeOpen(file, roots[source]);
      const {fd, stat} = opened;
      const identity = digest(JSON.stringify([source, session, stat.dev, stat.ino]));
      // Cheap change detector for polling clients: size and mtime move whenever the agent appends.
      const revision = digest(`${identity}:${stat.size}:${Math.floor(stat.mtimeMs)}`).slice(0, 16);
      if (!cursor && known && known === revision) return {available:true, source, revision, unchanged:true, messages:[], hasMore:false};
      const decoded = cursorValue(cursor, identity), end = decoded?.before ?? stat.size;
      if (end > stat.size) throw new BridgeError('history_changed', 'The history file changed. Refresh history.', 409);
      const start = Math.max(0, end - WINDOW), bytes = Buffer.alloc(end - start);
      fs.readSync(fd, bytes, 0, bytes.length, start);
      let position = 0;
      if (start > 0) { const newline = bytes.indexOf(10); position = newline < 0 ? bytes.length : newline + 1; }
      const messages = [];
      while (position < bytes.length) {
        const newline = bytes.indexOf(10, position);
        if (newline < 0) break; // A writer may still be appending this record.
        try {
          const record = JSON.parse(bytes.subarray(position, newline).toString('utf8'));
          const offset = start + position, recordEnd = start + newline + 1;
          parseHistoryRecords(record, source, digest(`${identity}:${offset}`).slice(0,32))
            .forEach((message, index) => messages.push({message, offset, recordEnd, index}));
        } catch { /* Ignore malformed records without exposing their contents. */ }
        position = newline + 1;
      }
      // A cursor may point within one transcript record when its display items exceed the page budget.
      // The record's end is retained so the next page can reread it and continue at the prior item.
      const eligible = decoded?.within === undefined ? messages : messages.filter(item =>
        item.offset < decoded.recordStart || (item.offset === decoded.recordStart && item.index < decoded.within));
      // Bound by conversation turns and serialized bytes. Tool steps stay between their turns across pages.
      const selected = []; let size = 0, turns = 0;
      for (let index = eligible.length - 1; index >= 0 && selected.length < 160; index--) {
        const item = eligible[index], length = Buffer.byteLength(JSON.stringify(item.message)), turn = item.message.role !== 'tool';
        if (size + length > PAGE_BYTES || (turn && turns >= 40)) break;
        selected.unshift(item); size += length; if (turn) turns++;
      }
      const first = selected[0];
      const cursorPosition = first?.index ? {identity, before:first.recordEnd, recordStart:first.offset, within:first.index} :
        {identity, before:first?.offset ?? start};
      const hasMore = cursorPosition.before > 0 && (start > 0 || eligible.length > selected.length);
      return {available:true, source, revision, messages:selected.map(item=>item.message), hasMore,
        ...(hasMore ? {nextCursor:encode(cursorPosition)} : {})};
    } catch (error) {
      if (error instanceof BridgeError) throw error;
      return unavailable('The conversation file could not be read safely. Live terminal output remains available.');
    } finally { if (opened) fs.closeSync(opened.fd); }
  }};
}
async function openCode(root, session, cursor) {
  if (session.kind !== 'id' || !/^ses_[A-Za-z0-9]{8,80}$/.test(session.value)) return unavailable('Herdr has not reported a supported OpenCode session ID.');
  let opened, db;
  try {
    const file = path.join(root, 'opencode.db');
    opened = safeOpen(file, root);
    const identity = digest(`${session.value}:${opened.stat.dev}:${opened.stat.ino}`);
    const decoded = cursorValue(cursor, identity);
    const {DatabaseSync} = await import('node:sqlite');
    db = new DatabaseSync(file, {readOnly:true});
    db.exec('PRAGMA query_only=ON; PRAGMA busy_timeout=250');
    // Keyset pagination is stable while the agent appends new messages.
    const rows = db.prepare("SELECT id,time_created,CASE WHEN json_valid(data) THEN json_extract(data,'$.role') END AS role FROM message WHERE session_id=? AND (time_created<? OR (time_created=? AND id<?)) ORDER BY time_created DESC,id DESC LIMIT 41")
      .all(session.value, decoded?.before ?? Number.MAX_SAFE_INTEGER, decoded?.before ?? Number.MAX_SAFE_INTEGER, decoded?.lastId ?? '\uffff');
    const messages=[]; let size=0, consumed=0, last;
    for (const row of rows.slice(0,40)) {
      // Clip extracted fields, never a serialized JSON record. Malformed neighbors
      // still advance the cursor but cannot hide valid messages on the page.
      if(!['user','assistant'].includes(row.role)){consumed++;last=row;continue;}
      const parts=db.prepare(`SELECT
        CASE WHEN json_valid(data) THEN json_extract(data,'$.type') END AS type,
        CASE WHEN json_valid(data) THEN substr(json_extract(data,'$.text'),1,8001) END AS text,
        CASE WHEN json_valid(data) THEN substr(json_extract(data,'$.tool'),1,120) END AS tool,
        CASE WHEN json_valid(data) THEN substr(COALESCE(json_extract(data,'$.state.output'),json_extract(data,'$.state.error')),1,8001) END AS output
        FROM part WHERE session_id=? AND message_id=? ORDER BY time_created,id LIMIT 100`).all(session.value,row.id);
      const rawText=parts.map(p=>p.type==='text'&&typeof p.text==='string'?p.text:p.type==='tool'?`${p.tool || 'Tool'}\n${typeof p.output==='string'?p.output:''}`:'').filter(Boolean).join('\n\n');
      const text=clip(rawText);
      const message={id:row.id,role:row.role,text,timestamp:date(row.time_created),...(rawText.length>8000?{truncated:true}:{})};
      const length=Buffer.byteLength(JSON.stringify(message));
      if(size+length>PAGE_BYTES)break;
      size+=length;consumed++;last=row;if(text)messages.unshift(message);
    }
    const hasMore=rows.length>consumed;
    return {available:true,source:'opencode',messages,hasMore,...(hasMore&&last?{nextCursor:encode({identity,before:last.time_created,lastId:last.id})}:{})};
  } catch (error) {
    if(error instanceof BridgeError)throw error;
    return unavailable('OpenCode history is unavailable for this database version. Live terminal output remains available.');
  } finally { db?.close(); if(opened)fs.closeSync(opened.fd); }
}
