import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {admit,cleanup} from '../src/admission.js';
function setup(t){const db=new DatabaseSync(':memory:');t.after(()=>db.close());for(const name of ['0001_auth.sql','0003_public.sql','0004_admission.sql'])db.exec(readFileSync(new URL('../migrations/'+name,import.meta.url),'utf8'));const stmt=(sql,args=[])=>({sql,args,bind:(...a)=>stmt(sql,a)});return {db,env:{DB:{prepare:stmt,async batch(statements){db.exec('BEGIN');try{const results=statements.map(s=>({results:db.prepare(s.sql).all(...s.args)}));db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}}}}};}
test('atomic admission never charges global quota for locally rejected requests',async t=>{const {env,db}=setup(t);const quotas=ip=>[{key:'global',limit:1000,window:86400},{key:ip,limit:2,window:3600}];for(let i=0;i<1000;i++)assert.equal(await admit(env,'attempt'+i,quotas('attacker'),100),i<2);assert.equal(await admit(env,'innocent',quotas('other'),100),true);assert.equal(db.prepare('SELECT SUM(count) n FROM quota_counters').get().n,6);});
test('concurrent atomic reservations cap all quotas; repeated operation cannot double-charge',async t=>{const {env,db}=setup(t),q=[{key:'global',limit:3,window:86400}];const accepted=await Promise.all(Array.from({length:20},(_,i)=>admit(env,'op'+i,q,100)));assert.equal(accepted.filter(Boolean).length,3);assert.equal(await admit(env,'op0',q,100),false);assert.equal(db.prepare('SELECT count FROM quota_counters').get().count,3);});
test('cooldown is sixty elapsed seconds across fixed minute boundaries',async t=>{const {env}=setup(t),q=[{key:'email:cooldown',limit:1,window:60,cooldown:true}];assert.equal(await admit(env,'first',q,119),true);assert.equal(await admit(env,'boundary',q,120),false);assert.equal(await admit(env,'early',q,178),false);assert.equal(await admit(env,'ready',q,179),true);});
test('scheduled cleanup removes expired records in bounded batches without logins',async t=>{const {env,db}=setup(t);const insert=db.prepare('INSERT INTO rate_limits VALUES (?,1,0)');for(let i=0;i<1005;i++)insert.run('expired'+i);db.prepare('INSERT INTO rate_limits VALUES (?,1,?)').run('live',Math.floor(Date.now()/1000)+300);await cleanup(env);assert.equal(db.prepare('SELECT COUNT(*) n FROM rate_limits').get().n,6);await cleanup(env);assert.equal(db.prepare('SELECT key FROM rate_limits').get().key,'live');});
