import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import net from 'node:net';
import {configurationPath} from '../src/configuration.js';import {defaultSessionOwner,assertPortAvailable,rollbackInstallation,localReadiness} from '../src/lifecycle.js';import {setupCompanion} from '../src/companion.js';
function fixture(t){const home=fs.mkdtempSync(path.join(os.tmpdir(),'lifecycle-test-'));t.after(()=>fs.rmSync(home,{recursive:true,force:true}));return home;}
test('legacy config does not follow companion-file existence and explicit config always wins',t=>{const home=fixture(t),root=path.join(home,'legacy');fs.mkdirSync(path.join(home,'.config/herdr-remote'),{recursive:true});fs.writeFileSync(path.join(home,'.config/herdr-remote/config.json'),'{}');assert.equal(configurationPath({root,explicit:undefined}),path.join(root,'config.json'));assert.equal(configurationPath({root,explicit:path.join(home,'custom.json')}),path.join(home,'custom.json'));});
test('session ownership detects custom-named enabled services without taking them over',()=>{const owner=defaultSessionOwner((_cmd,args)=>args.includes('list-units')?JSON.stringify([{unit:'my-work.service'}]):'ExecStart=/home/user/bin/herdr server\nActiveState=active\nUnitFileState=enabled');assert.deepEqual(owner,{kind:'external',unit:'my-work.service'});});
test('occupied port reports conflict without stopping any existing listener',async t=>{const server=net.createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());await assert.rejects(assertPortAvailable(server.address().port),/already in use/);assert.equal(server.listening,true);});
test('live manual default gets startup enabled without starting or restarting Herdr',async t=>{
 const home=fixture(t);fs.mkdirSync(path.join(home,'.local/bin'),{recursive:true});fs.writeFileSync(path.join(home,'.local/bin/herdr'),'#!/bin/sh\n',{mode:0o755});const calls=[];
 const result=await setupCompanion(['--portal','https://remote.example.com','--no-pair'],{home,configPath:path.join(home,'config.json'),checkPort:async()=>{},detectSocket:async()=>path.join(home,'.config/herdr/herdr.sock'),checkSocket:async()=>true,sessionOwner:()=>({kind:'manual'}),exec:(_cmd,args)=>calls.push(args),verifyHerdr:async()=>{},fetchImpl:async()=>new Response(JSON.stringify({id:'laptop',relayToken:'relay',claimToken:'claim',url:'https://remote.example.com'}))});
 assert.equal(result.config.sessionOwnership.kind,'companion');const herdrCalls=calls.filter(args=>args.includes('herdr-remote-session.service'));assert.equal(herdrCalls.length,1);assert.ok(herdrCalls[0].includes('enable'));assert.equal(herdrCalls[0].includes('--now'),false);assert.equal(herdrCalls[0].includes('restart'),false);
});
test('manual rollback changes only managed release target and companion service',t=>{const home=fixture(t),base=path.join(home,'install'),a=path.join(base,'releases/a'),b=path.join(base,'releases/b');for(const dir of [a,b]){fs.mkdirSync(path.join(dir,'bridge/src'),{recursive:true});fs.writeFileSync(path.join(dir,'bridge/src/cli.js'),'');}fs.symlinkSync(b,path.join(base,'current'));fs.writeFileSync(path.join(base,'previous'),a);const calls=[];rollbackInstallation(base,{exec:(_cmd,args)=>calls.push(args)});assert.equal(fs.realpathSync(path.join(base,'current')),a);assert.equal(fs.readFileSync(path.join(base,'previous'),'utf8'),b);assert.deepEqual(calls,[['--user','restart','herdr-remote-companion.service']]);});
test('strict routing refuses rollback to a pre-capability release',async t=>{
 const {rollbackCompatible}=await import('../src/upgrade-guard.js');const home=fixture(t),config=path.join(home,'config.json'),state=path.join(home,'state'),old=path.join(home,'old');fs.mkdirSync(state);fs.mkdirSync(old);fs.writeFileSync(config,JSON.stringify({stateDir:state}));assert.equal(rollbackCompatible(config,old),true);fs.writeFileSync(path.join(state,'routing-mode.json'),JSON.stringify({strict:true}));assert.equal(rollbackCompatible(config,old),false);fs.mkdirSync(path.join(old,'bridge/src'),{recursive:true});fs.writeFileSync(path.join(old,'bridge/src/routing-capabilities.js'),'');assert.equal(rollbackCompatible(config,old),true);
});
test('setup preserves externally managed default session ownership',async t=>{
 const home=fixture(t),calls=[];const result=await setupCompanion(['--portal','https://remote.example.com','--no-pair'],{home,configPath:path.join(home,'config.json'),checkPort:async()=>{},detectSocket:async()=>path.join(home,'.config/herdr/herdr.sock'),checkSocket:async()=>true,sessionOwner:()=>({kind:'external',unit:'my-work.service'}),exec:(_cmd,args)=>calls.push(args),verifyHerdr:async()=>{},fetchImpl:async()=>new Response(JSON.stringify({id:'external',relayToken:'relay',claimToken:'claim',url:'https://remote.example.com'}))});
 assert.deepEqual(result.config.sessionOwnership,{kind:'external',unit:'my-work.service'});assert.ok(calls.every(args=>!args.includes('my-work.service')&&!args.includes('herdr-remote-session.service')));assert.equal(fs.existsSync(path.join(home,'.config/systemd/user/herdr-remote-session.service')),false);
});
test('checkout launcher pins legacy commands but lets setup create independent companion config',async t=>{
 const {spawnSync}=await import('node:child_process'),home=fixture(t),bin=path.join(home,'bin');fs.mkdirSync(bin);fs.writeFileSync(path.join(bin,'node'),'#!/bin/sh\nprintf "%s" "${HERDR_REMOTE_CONFIG-unset}"\n',{mode:0o755});const env={...process.env,PATH:bin+':/usr/bin:/bin'};delete env.HERDR_REMOTE_CONFIG;
 const launcher=path.resolve('../ops/herdr-remote');assert.equal(spawnSync('bash',[launcher,'setup'],{env,encoding:'utf8'}).stdout,'unset');assert.equal(spawnSync('bash',[launcher,'serve'],{env,encoding:'utf8'}).stdout,path.resolve('config.json'));env.HERDR_REMOTE_CONFIG=path.join(home,'explicit.json');assert.equal(spawnSync('bash',[launcher,'setup'],{env,encoding:'utf8'}).stdout,env.HERDR_REMOTE_CONFIG);
});
